# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a954ea9804e948909e21f2d84e2aa19876350dbd270e7ed384b5110689b6e28602940a444db560d37c649be85c5d1505d67975091aa998d1b37fe4ebd891d14b

test:
  secret_key_base: abff9925369b73cd431b84ccfc9ca6c56428899030e03888ac9aed89dd10cb313600962f79dfe556c218a581333c93b5642fe4eb88177be12a52f6b29ae64d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
